### ISSUE TITLE
Crashes consistently

### ISSUE THREAD

**Issue by SteakySteaks** [sagirilover/SoAnimeSoftware#1]
it always crashes about 5 minutes or so after injection. also this is a external cheat not a internal

**Comment by SteakySteaks** [comment]
this cheat is just shit. it crashes every 5 seconds, the aimbot is bad, no configs, and half the features don't work properly. just fix this and actually make it internal and then ill use it

**Comment by sagirilover** [comment]
lol

**Comment by saintly2k** [comment]
I think you’d know, that this cheat is still in work and you cannot compare it to their software like Gamesense, Neverlose, etc. But hey, feel free to implement a Config system and improve the aufbot! …this is not as easy as you thought? Y e s , this is, why it hasn’t been implemented, you bigbrain.

**Comment by eugen1763** [comment]
curb your retardation
